"""Nox's configuration: four layers, one validated model.

`config/defaults.yaml` ships with Nox, `user.yaml` holds what the user changed, a profile file
adds a preset on top, and runtime overrides live in memory only. `load_config` merges them in that
order and returns a `NoxConfig`; see `nox.core.config.loader` for the merge and fallback rules.

The sections are grouped by what they are about: `core` (identity, paths, IPC, logging,
supervisor, plugins), `security` (security and privacy), `assistant` (voice, models, pet,
attention, memory, proactivity, sensors) and `features` (stream, game coaching, clips, project
management, creative apps, mobile companion). Every public name is re-exported here, so
`from nox.core.config import NoxConfig` keeps working whichever module a section lives in.
"""

from __future__ import annotations

from nox.core.config.assistant import (
    AiConfig,
    AiProvidersConfig,
    AiRouterConfig,
    AttentionConfig,
    ClaudeCodeProviderConfig,
    MemoryConfig,
    OllamaProviderConfig,
    PetConfig,
    ProactiveConfig,
    QuietHoursConfig,
    SensorForegroundConfig,
    SensorGameConfig,
    SensorIdleConfig,
    SensorResourcesConfig,
    SensorsConfig,
    SttConfig,
    TtsConfig,
    VoiceChannelsConfig,
    VoiceConfig,
)
from nox.core.config.core import (
    DATA_SUBDIRECTORIES,
    DEFAULT_DATA_DIR,
    HealthConfig,
    IdentityConfig,
    IpcConfig,
    LocaleConfig,
    LoggingConfig,
    PathsConfig,
    PluginsConfig,
    SupervisorConfig,
)
from nox.core.config.features import (
    CLIP_ROOTS,
    DEFAULT_CREATIVE_APP_PATTERNS,
    AppPattern,
    ClipsConfig,
    CreativeConfig,
    FunkenConfig,
    PmConfig,
    RelevanceConfig,
    RemoteConfig,
    RemoteNotificationsConfig,
    RlBudgetConfig,
    RlCalloutConfig,
    RlConfig,
    RlDetectionConfig,
    RlReplayConfig,
    RlRetentionConfig,
    RlVisionConfig,
    StreamChatConfig,
    StreamConfig,
    StreamTwitchConfig,
)
from nox.core.config.loader import (
    deep_merge,
    format_validation_error,
    load_config,
    profile_path,
    read_yaml_layer,
)
from nox.core.config.model import NoxConfig
from nox.core.config.security import (
    DEFAULT_LOOPBACK_ALLOWLIST,
    SECURITY_PROFILE_IDS,
    AuditConfig,
    CaptureConfig,
    PrivacyConfig,
    RetentionConfig,
    SecurityConfig,
    SecurityProfileId,
)
from nox.core.config.types import (
    ConfigError,
    ConfigWarning,
    ExpandedPath,
    OptionalExpandedPath,
    StrictSection,
    expand_path,
    require_ordered,
)

__all__ = [
    "CLIP_ROOTS",
    "DATA_SUBDIRECTORIES",
    "DEFAULT_CREATIVE_APP_PATTERNS",
    "DEFAULT_DATA_DIR",
    "DEFAULT_LOOPBACK_ALLOWLIST",
    "SECURITY_PROFILE_IDS",
    "AiConfig",
    "AiProvidersConfig",
    "AiRouterConfig",
    "AppPattern",
    "AttentionConfig",
    "AuditConfig",
    "CaptureConfig",
    "ClaudeCodeProviderConfig",
    "ClipsConfig",
    "ConfigError",
    "ConfigWarning",
    "CreativeConfig",
    "ExpandedPath",
    "FunkenConfig",
    "HealthConfig",
    "IdentityConfig",
    "IpcConfig",
    "LocaleConfig",
    "LoggingConfig",
    "MemoryConfig",
    "NoxConfig",
    "OllamaProviderConfig",
    "OptionalExpandedPath",
    "PathsConfig",
    "PetConfig",
    "PluginsConfig",
    "PmConfig",
    "PrivacyConfig",
    "ProactiveConfig",
    "QuietHoursConfig",
    "RelevanceConfig",
    "RemoteConfig",
    "RemoteNotificationsConfig",
    "RetentionConfig",
    "RlBudgetConfig",
    "RlCalloutConfig",
    "RlConfig",
    "RlDetectionConfig",
    "RlReplayConfig",
    "RlRetentionConfig",
    "RlVisionConfig",
    "SecurityConfig",
    "SecurityProfileId",
    "SensorForegroundConfig",
    "SensorGameConfig",
    "SensorIdleConfig",
    "SensorResourcesConfig",
    "SensorsConfig",
    "StreamChatConfig",
    "StreamConfig",
    "StreamTwitchConfig",
    "StrictSection",
    "SttConfig",
    "SupervisorConfig",
    "TtsConfig",
    "VoiceChannelsConfig",
    "VoiceConfig",
    "deep_merge",
    "expand_path",
    "format_validation_error",
    "load_config",
    "profile_path",
    "read_yaml_layer",
    "require_ordered",
]
