"""The name to payload mapping: which model belongs to which event name.

It lives apart from the models because it is the one place that has to know all of them,
and because a missing entry is a different kind of mistake from a wrong field - the catalogue
test walks this mapping against the names."""

from __future__ import annotations

from typing import Any

from pydantic import BaseModel

from nox.core.events.desktop import (
    ClipExported,
    ClipFailed,
    ClipRequested,
    ClipSaved,
    CodingSessionEnded,
    CodingSessionFailed,
    CodingSessionProgress,
    CodingSessionStarted,
    CreativeAppDetected,
    CreativeAppLeft,
    CreativeNoteWritten,
    CreativeScreenshotRequested,
    CreativeScreenshotResult,
    MemoryCreated,
    MemoryDeleted,
    MemoryIndexUpdated,
    PmFocusChanged,
    PmItemChanged,
    PrivacyZoneChanged,
    ProactiveNotification,
    ProactiveSuppressed,
    SensorForegroundChanged,
    SensorProcessEnded,
    SensorProcessStarted,
    SettingsChanged,
    TwitchAuthChanged,
    ViewShown,
)
from nox.core.events.mobile import (
    RemoteCommand,
    RemoteMessage,
    RemoteNotificationSent,
    RemotePaired,
    RemotePairingStarted,
    RemoteRevoked,
)
from nox.core.events.names import E
from nox.core.events.stream import (
    GameDetected,
    GameEnded,
    ObsAutoRestarted,
    ObsConnectionChanged,
    ObsCrashDetected,
    ObsDisconnected,
    ObsHealthChanged,
    ObsSceneChanged,
    RlCallout,
    RlEvent,
    RlMatchEnded,
    RlMatchStarted,
    RlReplayParsed,
    RlVisionAnalysis,
    RlVisionDetections,
    RlVisionDisabled,
    StreamEnded,
    StreamFunkenAwarded,
    StreamFunkenChanged,
    StreamMinigameEnded,
    StreamMinigameStarted,
    StreamModeChanged,
    StreamPreflightResult,
    StreamStarted,
    StreamViewerSeen,
    TwitchChatMessage,
    TwitchChatMoodChanged,
    TwitchCommandInvoked,
    TwitchConnectionChanged,
    TwitchDisconnected,
    TwitchEvent,
    TwitchModerationAction,
    TwitchResynced,
)
from nox.core.events.system import (
    AiRequestFailed,
    AiRequestStarted,
    AiResponseReady,
    AuditEntry,
    CaptureChanged,
    HealthChanged,
    HealthReport,
    KillSwitch,
    ModeChanged,
    PermissionDecided,
    PermissionRequested,
    PetStateChanged,
    PluginLifecycle,
    PrivacyModeChanged,
    StateChanged,
    TranscriptReady,
    TtsStarted,
    VoiceKillPhrase,
)

__all__ = ["PAYLOAD_MODELS", "validate_payload"]

PAYLOAD_MODELS: dict[str, type[BaseModel]] = {
    E.SYSTEM_HEALTH_CHANGED: HealthChanged,
    E.SYSTEM_MODE_CHANGED: ModeChanged,
    E.STATE_CHANGED: StateChanged,
    E.VOICE_TRANSCRIPT_READY: TranscriptReady,
    E.VOICE_KILL_PHRASE: VoiceKillPhrase,
    E.TTS_STARTED: TtsStarted,
    E.AI_REQUEST_STARTED: AiRequestStarted,
    E.AI_RESPONSE_READY: AiResponseReady,
    E.AI_REQUEST_FAILED: AiRequestFailed,
    E.PET_STATE_CHANGED: PetStateChanged,
    E.PRIVACY_MODE_CHANGED: PrivacyModeChanged,
    E.PRIVACY_CAPTURE_CHANGED: CaptureChanged,
    E.SECURITY_KILL_SWITCH: KillSwitch,
    E.SECURITY_PERMISSION_REQUESTED: PermissionRequested,
    E.SECURITY_PERMISSION_DECIDED: PermissionDecided,
    E.SECURITY_AUDIT: AuditEntry,
    E.PLUGIN_STARTED: PluginLifecycle,
    E.PLUGIN_STOPPED: PluginLifecycle,
    E.PLUGIN_FAILED: PluginLifecycle,
    E.HEALTH_REPORT: HealthReport,
    E.STREAM_STARTED: StreamStarted,
    E.STREAM_ENDED: StreamEnded,
    E.STREAM_MODE_CHANGED: StreamModeChanged,
    E.STREAM_PREFLIGHT_RESULT: StreamPreflightResult,
    E.STREAM_VIEWER_SEEN: StreamViewerSeen,
    E.STREAM_FUNKEN_AWARDED: StreamFunkenAwarded,
    E.STREAM_FUNKEN_CHANGED: StreamFunkenChanged,
    E.STREAM_MINIGAME_STARTED: StreamMinigameStarted,
    E.STREAM_MINIGAME_ENDED: StreamMinigameEnded,
    E.OBS_CONNECTED: ObsConnectionChanged,
    E.OBS_DISCONNECTED: ObsDisconnected,
    E.OBS_SCENE_CHANGED: ObsSceneChanged,
    E.OBS_HEALTH_CHANGED: ObsHealthChanged,
    E.OBS_CRASH_DETECTED: ObsCrashDetected,
    E.OBS_AUTO_RESTARTED: ObsAutoRestarted,
    E.TWITCH_CONNECTED: TwitchConnectionChanged,
    E.TWITCH_DISCONNECTED: TwitchDisconnected,
    E.TWITCH_RESYNCED: TwitchResynced,
    E.TWITCH_CHAT_MESSAGE: TwitchChatMessage,
    E.TWITCH_COMMAND_INVOKED: TwitchCommandInvoked,
    E.TWITCH_EVENT: TwitchEvent,
    E.TWITCH_CHAT_MOOD_CHANGED: TwitchChatMoodChanged,
    E.TWITCH_MODERATION_ACTION: TwitchModerationAction,
    E.GAME_DETECTED: GameDetected,
    E.GAME_ENDED: GameEnded,
    E.RL_MATCH_STARTED: RlMatchStarted,
    E.RL_MATCH_ENDED: RlMatchEnded,
    E.RL_EVENT: RlEvent,
    E.RL_REPLAY_PARSED: RlReplayParsed,
    E.RL_CALLOUT: RlCallout,
    E.REMOTE_MESSAGE: RemoteMessage,
    E.REMOTE_PAIRING_STARTED: RemotePairingStarted,
    E.REMOTE_PAIRED: RemotePaired,
    E.REMOTE_REVOKED: RemoteRevoked,
    E.REMOTE_COMMAND: RemoteCommand,
    E.REMOTE_NOTIFICATION_SENT: RemoteNotificationSent,
    E.CLIP_REQUESTED: ClipRequested,
    E.CLIP_SAVED: ClipSaved,
    E.CLIP_FAILED: ClipFailed,
    E.CLIP_EXPORTED: ClipExported,
    E.SENSOR_FOREGROUND_CHANGED: SensorForegroundChanged,
    E.CREATIVE_APP_DETECTED: CreativeAppDetected,
    E.CREATIVE_APP_LEFT: CreativeAppLeft,
    E.CREATIVE_NOTE_WRITTEN: CreativeNoteWritten,
    E.CREATIVE_SCREENSHOT_REQUESTED: CreativeScreenshotRequested,
    E.CREATIVE_SCREENSHOT_RESULT: CreativeScreenshotResult,
    E.PM_ITEM_CHANGED: PmItemChanged,
    E.PM_FOCUS_CHANGED: PmFocusChanged,
    E.PRIVACY_ZONE_CHANGED: PrivacyZoneChanged,
    E.SENSOR_PROCESS_STARTED: SensorProcessStarted,
    E.SENSOR_PROCESS_ENDED: SensorProcessEnded,
    E.CODING_SESSION_STARTED: CodingSessionStarted,
    E.CODING_SESSION_PROGRESS: CodingSessionProgress,
    E.CODING_SESSION_ENDED: CodingSessionEnded,
    E.CODING_SESSION_FAILED: CodingSessionFailed,
    E.PROACTIVE_NOTIFICATION: ProactiveNotification,
    E.PROACTIVE_SUPPRESSED: ProactiveSuppressed,
    E.MEMORY_CREATED: MemoryCreated,
    E.MEMORY_DELETED: MemoryDeleted,
    E.MEMORY_INDEX_UPDATED: MemoryIndexUpdated,
    E.SETTINGS_CHANGED: SettingsChanged,
    E.TWITCH_AUTH_CHANGED: TwitchAuthChanged,
    E.VIEW_SHOWN: ViewShown,
    E.RL_VISION_DETECTIONS: RlVisionDetections,
    E.RL_VISION_DISABLED: RlVisionDisabled,
    E.RL_VISION_ANALYSIS: RlVisionAnalysis,
}


# ---- Bus contract --------------------------------------------------------------------------------


def validate_payload(name: str, payload: dict[str, Any]) -> dict[str, Any]:
    """Validate a payload for a catalogued event name. Unknown names pass through unchanged."""
    model = PAYLOAD_MODELS.get(name)
    if model is None:
        return payload
    return model.model_validate(payload).model_dump(mode="json")
